site_name: argmerge
theme:
  favicon: img/bracket-logo.svg
  name: material
  logo: img/bracket-logo.svg
  palette:
    primary: green
  features:
    - navigation.tabs
nav:
  - Home: index.md
  - API Docs: API/main.md
  - Examples: examples.md
plugins:
  - search